SELECT TOP 1 HANGAR.number, HANGAR.capacity - COUNT(HANGAR.number) AS MAX_FREE_SPACE
FROM HANGAR
LEFT JOIN AIRPLANE 
ON HANGAR.number = AIRPLANE.hangar_id
GROUP BY HANGAR.number, HANGAR.capacity
ORDER BY MAX_FREE_SPACE DESC;