SELECT * FROM Q13

CREATE VIEW Q13 AS 
SELECT DISTINCT CORPORATION.name
FROM EMPLOYEE
LEFT JOIN MAINTAINS
ON MAINTAINS.employee_id = EMPLOYEE.SSN
INNER JOIN SERVICE
ON SERVICE.id = MAINTAINS.service_id
INNER JOIN AIRPLANE
ON AIRPLANE.reg# = SERVICE.plane_id
INNER JOIN OWNS
ON OWNS.plane_id = AIRPLANE.reg#
LEFT JOIN CORPORATION 
ON CORPORATION.id = OWNS.owner_id_corporation AND OWNS.owner_id_person IS NULL
LEFT JOIN PERSON 
ON PERSON.SSN = OWNS.owner_id_person AND OWNS.owner_id_corporation IS NULL
WHERE CORPORATION.name IS NOT NULL AND MAINTAINS.employee_id IS NULL

UNION ALL

SELECT DISTINCT PERSON.name
FROM EMPLOYEE
LEFT JOIN MAINTAINS
ON MAINTAINS.employee_id = EMPLOYEE.SSN
INNER JOIN SERVICE
ON SERVICE.id = MAINTAINS.service_id
INNER JOIN AIRPLANE
ON AIRPLANE.reg# = SERVICE.plane_id
INNER JOIN OWNS
ON OWNS.plane_id = AIRPLANE.reg#
LEFT JOIN CORPORATION 
ON CORPORATION.id = OWNS.owner_id_corporation AND OWNS.owner_id_person IS NULL
LEFT JOIN PERSON 
ON PERSON.SSN = OWNS.owner_id_person AND OWNS.owner_id_corporation IS NULL
WHERE PERSON.name IS NOT NULL AND MAINTAINS.employee_id IS NULL



