use A2

--Task 17

SELECT AIRPLANE.name, AIRPLANE.reg#
FROM AIRPLANE
LEFT JOIN OWNS ON AIRPLANE.reg# = OWNS.plane_id
LEFT JOIN CORPORATION ON OWNS.owner_id_corporation = CORPORATION.id
left join SERVICE on SERVICE.plane_id = AIRPLANE.reg#
left join MAINTAINS on MAINTAINS.service_id = SERVICE.id
left join EMPLOYEE on EMPLOYEE.SSN = MAINTAINS.employee_id
--LEFT JOIN EMPLOYEE ON SERVICE. = EMPLOYEE.SSN
WHERE CORPORATION.id IS NULL AND EMPLOYEE.shifts = 'day';
