SELECT TOP 5 EMPLOYEE.name, SUM(HOURS) AS TOTAL_HOURS
FROM EMPLOYEE
INNER JOIN MAINTAINS
ON EMPLOYEE.SSN = MAINTAINS.employee_id
INNER JOIN SERVICE
ON MAINTAINS.service_id = SERVICE.id
GROUP BY EMPLOYEE.name, service_id, hours
ORDER BY SUM(HOURS) DESC



