SELECT PILOT.SSN, PILOT.name, COUNT(PILOT.SSN)
FROM PLANE_TYPE
LEFT JOIN FLIES
ON FLIES.plane_id = PLANE_TYPE.model_no
LEFT JOIN PILOT
ON FLIES.pilot_id = PILOT.SSN
GROUP BY PILOT.SSN, PILOT.name
